import Head from 'next/head'
import './globals.css'
import { Lora } from 'next/font/google'
import Navbar from '@components//Navbar'
import Foot from '@components//Footer'

const lora = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'LK Creatives',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" /> {/* Update the href attribute accordingly */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={lora.className}>
        <Navbar />
        {children}
        <Foot />
        </body>
    </html>
  )
}
