
import './globals.css'
import { Lora } from 'next/font/google'
import Navbar from '@components//Navbar'
import Foot from '@components//Footer'

const lora = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={lora.className}>
        <Navbar />
        {children}
        <Foot />
        </body>
    </html>
  )
}
